# Generated by Django 3.2.7 on 2021-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('MW', 'MOST WATCHED'), ('MT', 'MOST WATCHED2'), ('MR', 'MOST WATCHED3'), ('TR', 'TOP RATED'), ('TT', 'TOP RATED2'), ('FT', 'FEATURED MOV')], max_length=2),
        ),
    ]
