# Generated by Django 3.2.7 on 2021-09-22 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE'), ('horror', 'HORROR')], max_length=10)),
                ('status', models.CharField(choices=[('MW', 'MOST WATCHED'), ('MT', 'MOST WATCHED2'), ('MR', 'MOST WATCHED3'), ('TR', 'TOP RATED'), ('TT', 'TOP RATED2'), ('FT', 'FEATURED MOV')], max_length=2)),
                ('year', models.DateField()),
                ('cast', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
