# Generated by Django 3.2.7 on 2021-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_tv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tv',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE'), ('horror', 'HORROR'), ('thriller', 'THRILLER'), ('animation', 'ANIMATION')], max_length=10),
        ),
    ]
