# Generated by Django 3.2.7 on 2021-09-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20210922_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE'), ('horror', 'HORROR'), ('thriller', 'THRILLER'), ('animation', 'ANIMATION'), ('advanture', 'ADVANTURE')], max_length=10),
        ),
    ]
